### ISSUE TITLE
Error 500 when filtering parameters with channel 2

### ISSUE THREAD

**Issue by lyssdod** [IonosatMicro/promis-backend#83]
Looks like remains of profiler: 

```
[10/Apr/2017 03:03:22] "GET /en/api/parameters/?channel=1 HTTP/1.0" 200 225
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.6/site-packages/django_extensions/management/commands/runprofileserver.py", line 244, in handler
    os.rename(profname, profname2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/sync//profiling/en.api.parameters.1491793402.prof' -> '/usr/src/app/sync//profiling/en.api.parameters.000078ms.1491793402.prof'
[10/Apr/2017 03:03:22] "GET /en/api/parameters/?channel=2 HTTP/1.0" 500 59
```

**Comment by landswellsong** [comment]
Whoah I sense we're gonna patch upstream again ^_^

**Comment by landswellsong** [comment]
Hmm, I wonder what's going on here. Your code produces:
```
[10/Apr/2017 07:02:42] "GET /en/api/parameters/?channel=2 HTTP/1.0" 200 228
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
[10/Apr/2017 07:02:42] "GET /en/api/projects HTTP/1.0" 200 640
  File "/usr/local/lib/python3.6/site-packages/django_extensions/management/commands/runprofileserver.py", line 244, in handler
    os.rename(profname, profname2)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/sync//profiling/en.api.parameters.1491807762.prof' -> '/usr/src/app/sync//profiling/en.api.parameters.000075ms.1491807762.prof'
[10/Apr/2017 07:02:42] "GET /en/api/parameters/?channel=1 HTTP/1.0" 500 59
```

Manually hitting those entries gives the following instead:
```
[10/Apr/2017 07:04:01] "GET /en/api/parameters/?channel=1 HTTP/1.0" 200 7107
[10/Apr/2017 07:04:06] "GET /en/api/parameters/?channel=2 HTTP/1.0" 200 7110
```

I'll try to come up with a test.
